apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
resources:
  - namespace.yaml
  - snapshot/crd
helmCharts:
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    releaseName: democratic-csi
    namespace: democratic-csi
    version: 0.14.x
    valuesFile: values.yaml
generators:
  - ksops-generator.yaml
